name: Shivangi Khandelwal

# Provide the name for all of your other GitHub repos that relate to this class.
# If I substitute your username and the repo name in a GitHub URL like this:
#    `https://github.com/YOUR_GITHUB_USERNAME/REPO_NAME`
# I should find your repository.
repo_names:
https://github.com/shivangik11/Mapping
  

# Provide any URLs for your Videos
10-ux-ui-criticism:
  Good - https://youtu.be/UlAeAFDDPvM
  Bad - https://youtu.be/NKUu1J-QZKk

# Provide any URLs for your Data Models assignment
11-models-from-data:
https://github.com/shivangik11/Mapping

project-check-in-1:
https://github.com/shivangik11/ATLAS-iOS-Fall-22/issues/2#issue-1407009053

application design:
https://github.com/shivangik11/application-design

 
