name: Shivangi Khandelwal

# Provide the name for all of your other GitHub repos that relate to this class.
# If I substitute your username and the repo name in a GitHub URL like this:
#    `https://github.com/YOUR_GITHUB_USERNAME/REPO_NAME`
# I should find your repository.
repo_names:
  

# Provide any URLs for your Videos
10-ux-ui-criticism:
  Good - http://https://youtu.be/UlAeAFDDPvM
  Bad - http://https://youtu.be/NKUu1J-QZKk

# Provide any URLs for your Data Models assignment
11-models-from-data:
 
